template/portainer-v2-arm64.json

Added in Reactive Resume

---

template/portainer-v2-arm32.json
template/portainer-v2-arm64.json

Change a few environment variables from `bool` to `string` so `Copy as custom` works
This also fix the issue on #1.
This PR fix the issue when trying to Copy as custom from the template list.
Template 32 and 64 bits

Fix error when Copy as Custom

---

docs/macvlan_setup.md

Update `macvlan_setup.md` tutorial. Instead of changing `/etc/network/interfaces` that was not present on **Raspberry Pi OS** it uses `ip` command and a `systemd` service. This should be simpler to implement and work across different OSes.
Improve documentation
- `macvlan_setup.md`

Update macvlan tutorial

---

template/portainer-v2-arm32.json
template/portainer-v2-arm64.json

Just to fix a typo on my previous PR. Replacing `bookstrap` with `bookstack` also adding a name to template to reduce number of inputs when deploying

Fix Bookstack typo

---

pi-hosted_template/template/portainer-v2.json
template/portainer-v2-arm32.json
template/portainer-v2-arm64.json

Upgrade Rutorrent template

---

docs/AppList.md
template/portainer-v2-arm32.json
template/portainer-v2-arm64.json

Deprecate **Airsonic** and add **Airsonic Advanced** in place.
Keep softwares up to date.
Both templates 32 and 64 bits

Deprecate Airsonic and Add Airsonic Advanced

---

docs/AppList.md
docs/DocumentList.md
pi-hosted_template/template/portainer-v2.json
stack/your-spotify.yml
template/apps/your-spotify.json
template/portainer-v2-arm32.json
template/portainer-v2-arm64.json

A new app called Your Spotify was added.
It's a cool dashboard that shows your Spotify history.
I've added 2 files.
- pi-hosted/template/your-spotify.json
- pi-hosted/stack/your-spotify.yml

Added Your Spotify Dashboard app

---

template/apps/archisteamfarm.json

I added [ArchiSteamFarm](https://github.com/JustArchiNET/ArchiSteamFarm/) to the templates
It's neat to have it there
template/apps/archisteamfarm.json

Added ArchiSteamFarm

---

template/apps/qflood.json

I added qFlood.
It's neat to have it there.
template/apps/qflood.json

Added qFlood

---

install_unpoller.sh

Update unpoller.conf download URL
Current URL result 404
URL update
Rename script to keep inline with another script `install_xxx.sh`

fix unpoller conf download url

---

configs/dashboard_by_oijkn.json

Current grafana dashboard json not working with `latest` `0.39.3` cadvisor, `0.38.8` will.
Update dashboard json to fix missing bits when using newer cadvisor
update json dashboard inline with https://github.com/oijkn/Docker-Raspberry-PI-Monitoring/blob/b6ea27567400d22ff710ddbacb8ba5fb46261151/grafana/dashboard_by_oijkn.json

update grafana json to oijkn updated dashboard

---

.github/pull_request_template.md

Fix format and cleanup PR template
Current PR template so intimidate
Some listing cleanup, font size change
-
-
-
-
-

fix PR template format and less intimidating

---

stack/yourls.yml

Adding missing stack Parmater to stack profile

---

build/info.json
template/apps/snippet-box.json
template/apps/wireguard-server.json

Update Youtube videos and link video to apps
Keep it up to date
- `build/info.json`
- `template/apps/snippet-box.json` -> Video 14
- `template/apps/wireguard-server.json` -> Video 13

Update Youtube videos

---

stack/raspberrypi-monitoring.yml

Grafana latest is the stable branch, switched main branch to latest
Not that important, but stability is preferable
Grafana docker image main branch changed to latest branch
No
No
No

updated grafana main branch to latest branch

---

build/info.json
template/apps/deluge.json
template/apps/go-socks5-proxy.json
template/apps/rustdesk.json
template/apps/samba.json

Update Youtube Videos list and related apps
Keep repo up to date

Update Youtube Videos list

---

template/apps/wireguard-server.json

Fix Wireguard App
App was using both image and stack file. Image section removed

Fix Wireguard App

---

tools/update_libseccomp2.sh

this is ia fix for #56 , there must have been an issue with the previous package, because its been deleted, not just updated

update debian package name, which changed on 2022-07-23

---

tools/update_libseccomp2.sh

fixup for previous patch (#57) mentioned in issue #56

fixup for 32bit libseccomp2 patch

---

build/joinApps.sh

Include multiple videos into Template
It was missing on the previous patch.
`joinapps.sh` script to parse multiple videos. It also includes the channel name. Multiples videos are shown as list

Update joinapps.sh to include multiple videos and channel

---

.gitignore

ignore vscode config folder

---

template/apps/watchtower.json

See: https://containrrr.dev/watchtower/arguments/#cleanup

Cleanup image when image is updated with watchtower

---

template/apps/cloudflared-tunnel.json

The command used: ```--token $TUNNEL_TOKEN``` not read correctly, maybe related to how the image build. Using ```tunnel run``` will read the ```$TUNNEL_TOKEN``` correctly

Revert cloudflared-tunnel.json

---

template/apps/archisteamfarm.json

Changed all volume bindings from /portainer/Files/AppData/ArchiSteamFarm/... to /portainer/Files/AppData/Config/ArchiSteamFarm/...
Changed these to use the same path as every other templates
template/apps/archisteamfarm.json

Fixed ArchiSteamFarm template volume bindings

---

.github/workflows/automategeneration.yml
template/apps/authelia.json

I only changed the url to the right documentation.
Personally i have no experience with Authelia, but if @lgaudreau is correct, we may need to consider making it a stack like the rpi-monitor?
https://github.com/pi-hosted/pi-hosted/issues/40

Partially fixes: #40

---

configs/rpi_dashboard/amd_rpi_dashboard.json

Replaced `thermal-temp` to `x86_pkg_temp`
Making temp graph and gauge works
Replaced `thermal-temp` to `x86_pkg_temp`
Temp gauge and bar

Fixing dashboard temp

---

.github/workflows/automategeneration.yml

Trigger build on each branch for testing

---

pi-hosted_template/template/portainer-v2.json
template/apps/deemix.json
template/portainer-v2-amd64.json
template/portainer-v2-arm32.json
template/portainer-v2-arm64.json

Found a configuration error in the port mapping.  As it currently is deploying deemix will result in a nonfunctional instance because of a bad port mapping.
Deemix is currently non-functional
port mapping update
N/A
port mapping in deemix.json
mapping from 9666:9666/tcp to 9666:6595/tcp
N/A
N/A

Configuration Error

---

template/apps/booksonic.json
template/apps/cardigann.json
template/apps/codiad.json
template/apps/couchpotato.json
template/apps/dradis.json
template/apps/kodi-headless.json
template/apps/libreddit.json

Templates screening for more updated status
* Add DEPRECATED status on some template
* Remove arm32 & arm64 or dradis
* Update libreddit docker image url

Templates Screening

---

configs/rpi_dashboard/amd_rpi_dashboard.json

Fi missing CPU usage on the dashboard
Fix grafana query
Remove unused query, `the query is there but not showing correctly`
-
-

amd64 dashboar cpu usage fix

---

template/apps/Firefox.json

Change in url for firefox image

fixed firefox image

---

pi-hosted_template/template/portainer-v2.json

Just replaced the link in the v2.json file

Fix oled stats picture
